services:
  microservice-db:
    image: postgres:17-alpine3.20
    container_name: api-db
    restart: always
    shm_size: 128mb
    ports:
      - "5678:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./volumes/postgres-db:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d

  auth-api-img:
    container_name: auth-api-container
    restart: always
    env_file: ./auth-api/.env
    depends_on:
      - microservice-db
    build:
      context: ./auth-api
      dockerfile: Dockerfile
    ports:
      - "7500:7500"
    volumes:
      - ./auth-api:/api/auth-api
      - /api/auth-api/node_modules #  container manages its own node_modules. Fix esbuild architecture mismatch between container & host.
    command: pnpm dev

  posts-api-img:
    container_name: posts-api-container
    restart: always
    env_file: ./posts-api/.env
    depends_on:
      - microservice-db
    build:
      context: ./posts-api
      dockerfile: Dockerfile
    ports:
      - "7600:7600"
    volumes:
      - ./posts-api:/api/posts-api
      - /api/posts-api/node_modules
    command: pnpm dev
